-- CreateEnum
CREATE TYPE "LabArea" AS ENUM ('SOIL_MECHANICS', 'CONCRETE_AGGREGATES', 'MINE_INTERIOR');

-- AlterTable
ALTER TABLE "Sample" ADD COLUMN     "area" "LabArea" NOT NULL DEFAULT 'SOIL_MECHANICS';
